language: java
install: ./gradlew assemble
script: travis_wait ./gradlew check
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/frontend/node_modules/
before_install:
- sudo apt-get install jq
- wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
after_success:
- bash <(curl -s https://codecov.io/bash) -t 5afb1257-baa4-4faa-9b91-7054bc394123
- java -jar ~/codacy-coverage-reporter-assembly-latest.jar l Kotlin -r ./build/reports/jacoco/report.xml -t 9b89e61214804564afdd8921d4c515d6