# This is a sample build configuration for Java â€“ Gradle.
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: java:8

pipelines:
    default:
      - step:
          caches:
            - gradle
            - maven
          script:
             - chmod +x gradlew
             - ./gradlew build
    branches:  # Pipelines that run automatically on a commit to a branch
      build:
       - step:
           caches:
             - gradle
             - maven
           script:
             - chmod +x gradlew
             - ./gradlew build
    custom: # Pipelines that are triggered manually
       build:
        - step:
            caches:
             - gradle
             - maven
            script:
             - chmod +x gradlew
             - ./gradlew build