# This is a sample build configuration for Java – Gradle.
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: java:8

options:
  max-time: 40
  size: 2x 
  
pipelines:
    default:
      - step:
          caches:
            - gradle
            - maven
            - nodemodules
          script:
             - chmod +x gradlew
             - ./gradlew build
    branches:  # Pipelines that run automatically on a commit to a branch
      build:
       - step:
           caches:
             - gradle
             - maven
             - nodemodules
           script:
             - chmod +x gradlew
             - ./gradlew build
    custom: # Pipelines that are triggered manually
      build:
        - step:
            caches:
             - gradle
             - maven
             - nodemodules
            script:
             - chmod +x gradlew
             - ./gradlew build
      full-deliver:
        - step:
            caches:
             - gradle
             - maven
             - nodemodules
            script:
             - echo "Starting build..."
             - chmod +x gradlew
             - ./gradlew build
             - bash deploy/deliver-backend.sh
             - bash deploy/deliver-frontend.sh
      frontend-deliver:
        - step:
            caches:
             - gradle
             - maven
             - nodemodules
            script:
             - echo "Starting frontend build..."
             - chmod +x gradlew
             - cd frontend
             - ../gradlew build
             - cd ..
             - bash deploy/deliver-frontend.sh


definitions:
    caches:
         nodemodules: frontend/node_modules