# This is a sample build configuration for Java â€“ Gradle.
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: java:8

pipelines:
    default:
      - step:
          caches:
            - gradle
            - maven
            - nodemodules
          script:
             - chmod +x gradlew
             - ./gradlew build
    branches:  # Pipelines that run automatically on a commit to a branch
      build:
       - step:
           caches:
             - gradle
             - maven
             - nodemodules
           script:
             - chmod +x gradlew
             - ./gradlew build
    custom: # Pipelines that are triggered manually
       build:
        - step:
            caches:
             - gradle
             - maven
             - nodemodules
            script:
             - echo "Starting build..."
             - chmod +x gradlew
             - ./gradlew build
             - ls -l backend/build/libs/backend.jar
             - echo "test-new" > data
             - ls -l data
             - ls -la ~/.ssh/
             - echo "Trying to copy"
             - scp -i ~/.ssh/config backend/build/libs/backend.jar  bitbucket@catalog.reflexia.com:/home/bitbucket/__backend__.jar
             - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"backend/build/libs/backend.jar"
             - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/config backend/build/libs/backend.jar bitbucket@catalog.reflexia.com:/home/bitbucket/___backend___.jar
             - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/config  bitbucket@catalog.reflexia.com:/home/bitbucket/___backend___.jar .
             - ls -l ___backend___.jar
             - cd frontend
             - jar cf ../frontend.jar build
             - cd ..
             - scp -i ~/.ssh/config  frontend.zip bitbucket@catalog.reflexia.com:/home/bitbucket/frontend.zip
       deploy-sandox:
        - step:
            caches:
             - gradle
             - maven
             - nodemodules
            script:
             - echo "Starting build..."
             - ls


definitions:
    caches:
         nodemodules: frontend/node_modules